# Generated by Django 2.1.3 on 2018-11-25 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import strativerse.geometry


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'aliases',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='attachment', max_length=55)),
                ('key', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', message='Must only contain alphanumerics or the underscore')])),
                ('comment', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='attachments')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=55)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=55)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'contact info',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_wkt', models.TextField(blank=True, validators=[strativerse.geometry.validate_wkt])),
                ('geo_error', models.FloatField(default=0)),
                ('geo_elev', models.FloatField(default=0)),
                ('geo_elev_error', models.FloatField(default=0)),
                ('geo_xmin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_xmax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_type', models.CharField(blank=True, editable=False, max_length=55)),
                ('recursive_depth', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('water_body', 'Water Body'), ('glacier', 'Glacier'), ('bog', 'Bog'), ('geopolitical_unit', 'Geopolitical Unit'), ('region', 'Region')], default='feature', max_length=55)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='strativerse.Feature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[^/][a-zA-Z_/]+[^/]$')])),
                ('description', models.TextField(blank=True)),
                ('preparation', models.CharField(max_length=255)),
                ('instrumentation', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_names', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('orc_id', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$', message='Value must be a valid ORCID (0000-0000-0000-0000)')])),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['last_name', 'given_names'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=55, unique=True)),
                ('type', models.CharField(choices=[('article', 'article'), ('article-journal', 'article-journal'), ('article-magazine', 'article-magazine'), ('article-newspaper', 'article-newspaper'), ('bill', 'bill'), ('book', 'book'), ('broadcast', 'broadcast'), ('chapter', 'chapter'), ('dataset', 'dataset'), ('entry', 'entry'), ('entry-dictionary', 'entry-dictionary'), ('entry-encyclopedia', 'entry-encyclopedia'), ('figure', 'figure'), ('graphic', 'graphic'), ('interview', 'interview'), ('legal_case', 'legal_case'), ('legislation', 'legislation'), ('manuscript', 'manuscript'), ('map', 'map'), ('motion_picture', 'motion_picture'), ('musical_score', 'musical_score'), ('pamphlet', 'pamphlet'), ('paper-conference', 'paper-conference'), ('patent', 'patent'), ('personal_communication', 'personal_communication'), ('post', 'post'), ('post-weblog', 'post-weblog'), ('report', 'report'), ('review', 'review'), ('review-book', 'review-book'), ('song', 'song'), ('speech', 'speech'), ('thesis', 'thesis'), ('treaty', 'treaty'), ('webpage', 'webpage')], max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('DOI', models.CharField(blank=True, max_length=255)),
                ('URL', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_wkt', models.TextField(blank=True, validators=[strativerse.geometry.validate_wkt])),
                ('geo_error', models.FloatField(default=0)),
                ('geo_elev', models.FloatField(default=0)),
                ('geo_elev_error', models.FloatField(default=0)),
                ('geo_xmin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_xmax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_type', models.CharField(blank=True, editable=False, max_length=55)),
                ('name', models.CharField(max_length=255)),
                ('date_collected', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('medium', models.CharField(choices=[('lake_sediment', 'Lake Sediment'), ('marine_sediment', 'Marine Sediment'), ('glacier_ice', 'Glacier Ice'), ('peat', 'Peat'), ('lake_water', 'Lake Water'), ('river_water', 'River Water'), ('ocean_water', 'Ocean Water'), ('wood', 'Wood'), ('surficial_sediment', 'Surficial sediment'), ('rock', 'Rock'), ('mollusk_shell', 'Mollusk shell'), ('coral', 'Coral'), ('speleothem', 'Speleothem'), ('sclerosponge', 'Sclerosponge'), ('air', 'Air'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=55)),
                ('type', models.CharField(choices=[('samples', 'Samples'), ('core', 'Core'), ('section', 'Section'), ('sensor', 'Sensor'), ('other', 'Other')], max_length=55)),
                ('resolution', models.FloatField(blank=True, default=None, null=True)),
                ('min_year', models.FloatField(blank=True, default=None, null=True)),
                ('max_year', models.FloatField(blank=True, default=None, null=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strativerse.Feature')),
            ],
            options={
                'ordering': ['date_collected'],
            },
        ),
        migrations.CreateModel(
            name='RecordAuthorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assisted', 'Assisted'), ('collected', 'Collected'), ('funded', 'Funded'), ('analyzed', 'Analyzed'), ('published', 'Published'), ('maintains', 'Maintains')], default='assisted', max_length=55)),
                ('order', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_authorships', to='strativerse.Person')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_authorships', to='strativerse.Record')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecordParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=55)),
                ('position_units', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('min_value', models.FloatField(blank=True, default=None, null=True)),
                ('max_value', models.FloatField(blank=True, default=None, null=True)),
                ('mean_value', models.FloatField(blank=True, default=None, null=True)),
                ('median_value', models.FloatField(blank=True, default=None, null=True)),
                ('max_value_year', models.FloatField(blank=True, default=None, null=True)),
                ('min_value_year', models.FloatField(blank=True, default=None, null=True)),
                ('max_value_position', models.FloatField(blank=True, default=None, null=True)),
                ('min_value_position', models.FloatField(blank=True, default=None, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_parameters', to='strativerse.Parameter')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_parameters', to='strativerse.Record')),
            ],
            options={
                'ordering': ['parameter__name'],
            },
        ),
        migrations.CreateModel(
            name='RecordReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('refers_to', 'Refers to'), ('contains_data_from', 'Contains data from')], default='refers_to', max_length=55)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_uses', to='strativerse.Publication')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_uses', to='strativerse.Record')),
            ],
            options={
                'ordering': ['publication__date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='tag', max_length=55)),
                ('key', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', message='Must only contain alphanumerics or the underscore')])),
                ('value', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['type', 'key'],
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='strativerse.Person'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorships', to='strativerse.Person'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='strativerse.Publication'),
        ),
        migrations.AddField(
            model_name='alias',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='strativerse.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('content_type', 'object_id', 'type', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('content_type', 'object_id', 'type', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('person', 'alias')},
        ),
    ]
