# Generated by Django 2.1.3 on 2018-11-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
