# Generated by Django 2.1.3 on 2018-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0002_auto_20181201_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
