# Generated by Django 2.1.3 on 2018-12-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0002_auto_20181219_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='instrumentation',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='preparation',
        ),
    ]
