# Generated by Django 2.1.3 on 2018-11-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0002_auto_20181126_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.TextField(),
        ),
    ]
