# Generated by Django 2.1.3 on 2018-12-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0003_auto_20181225_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='strativerse.Feature'),
        ),
    ]
