# Generated by Django 2.1.3 on 2018-11-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0003_auto_20181126_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='URL',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
