# Generated by Django 2.1.3 on 2018-12-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0004_auto_20181225_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'people'},
        ),
    ]
