# Generated by Django 2.1.3 on 2018-11-29 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0004_auto_20181127_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordparameter',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='max_value_position',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='max_value_year',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='mean_value',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='median_value',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='min_value_position',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='min_value_year',
        ),
        migrations.RemoveField(
            model_name='recordparameter',
            name='position_units',
        ),
        migrations.AddField(
            model_name='record',
            name='position_units',
            field=models.CharField(blank=True, default='cm', max_length=55),
        ),
        migrations.AddField(
            model_name='record',
            name='published',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=55),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='instrumentation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='preparation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='slug',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[^/][a-zA-Z0-9_/-]+[^/]$')]),
        ),
        migrations.AlterField(
            model_name='recordparameter',
            name='units',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
