# Generated by Django 2.1.3 on 2018-11-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strativerse', '0005_auto_20181129_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordauthorship',
            options={'ordering': ['order', 'id']},
        ),
    ]
